---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      changed_when: false

    - name: Install basic dependencies
      ansible.builtin.apt:
        name:
          - sudo
          - curl
          - wget
          - ca-certificates
          - gnupg
          - lsb-release
          - apt-transport-https
          - python3-debian
        state: present
